#define MAJOR 3
#define MINOR 0
#define PATCH 1
#define BUILD 920

// #define VERSION MACROS
#define VERSION MAJOR.MINOR
#define VERSION_AR MAJOR,MINOR,PATCH,BUILD
#define VERSION_STR MAJOR##.##MINOR##.##PATCH##.##BUILD
